### ISSUE TITLE
No function available where when property can be passed in Microsoft.Extensions.Caching.StackExchangeRedis package in the Set function

### ISSUE THREAD

**Issue by Geet2009** [cnblogs/ServiceStackRedisCache#4]
In redis stackexchange implementation StringSetAsync(key, item, expireTimeSpan, When.NotExists) is available where we can pass the When to set in the redis cache but equivalent is not available in the Microsoft.Extensions.Caching.StackExchangeRedis package. Please help.

**Comment by cnblogs-dudu** [comment]
Reimplemented with latest ServiceStack.Redis in #8. Please try 2.1.0.

**Comment by Geet2009** [comment]
Looks like I added the issue at wrong place. Please close it appropriately.
